# -+- Pronouns Plugin -+-

# -=- Created By JayieWayie -=-
# -_- Created for GrapeSMP -_-

# Regarding Placeholders.
# Please use PlaceholderAPI. No ecloud download required.

# %pronouns_set% - shows pronouns set. - You can use this in essentialschat to show the pronouns in chat.
# %new_pronouns% - shows newly set pronouns.
# %player% - shows player name.
# %moderator% - shows moderator name.

#Database
Address: 'localhost'
Port: '3306'
Username: 'root'
Password: ''
Database: ''


# PrefixValue
# The Prefix is sent before ALL message in the plugin.

Prefix: '&8[&6Pronouns&8]'

# Error Messages

InvalidArgument: '&4Error404: &cCommand not found.'
InvalidInputs: '&4Error404: Invalid Inputs. &cUse /pronouns help.'
InvalidSender: '&4Error404: &cYou must be a player to run commands.'
NoPermission: '&4Error404: &cNo Permission!'

# Pronouns

Pronouns:
  - 'he/him'
  - 'she/her'
  - 'they/them'
  - 'he/they'
  - 'she/they'
  - 'Any'

# Player Messages

Success: 'Pronouns set to %new_pronouns%.'

# Sent to the player using /pronouns check (online player).
PronounsCheck:
  - '&7-+-+-+- &6Pronouns &7-+-+-+-'
  - ''
  - '- &6Username: %player%'
  - '- &6Pronouns: %pronouns_set%'
  - ''

# Sent to players using /pronouns help.
HelpMessage:
  - '&7-+-+-+- &6Pronouns Help &7-+-+-+-'
  - ''
  - '&6/pronouns set (pronouns) - Allows the user to change their pronouns.'
  - '&6/pronouns list - Allows a user to view the available pronouns.'

# Sent to the player on /pronouns reload.
ReloadMessage: '&aReload Complete.'

# Sent to the moderator who does /apronouns forceset.
forceset_ModMessage: 'set pronouns for %player% to %new_pronouns%'
forceset_PlayerMessage: 'pronouns set to %new_pronouns% by %moderator%'

# Permissions

# ALL Default Perms - pronouns.default
# ALL Perms - pronouns.*
# Set - Default - pronouns.set
# Color - Default - pronouns.color
# ForceSet - Admin - pronouns.forceset
# Reload - Admin - pronouns.reload
